[logging]
name = "Logging"
icon = "format_list_numbered"
description = "Log events/changes in your server."


[welcome]
name = "Welcome"
icon = "waving_hand"
description = "Welcome incoming members to the server."


[supporter-announcements]
name = "Supporter Announcements"
icon = "campaign"
description = "Announce new boosters and other server supporters by role."


[xp]
name = "XP"
icon = "sort"
description = "Server experience system to reward active members."

[xp.commands.top]
name = "Top"
icon = "leaderboard"
description = "Get top users by XP."
ghost = true

[xp.commands.rank]
name = "Rank"
icon = "military_tech"
description = "Get a user's XP and rank."
ghost = true

[xp.commands.xp]
name = "Manage XP"
icon = "sort"
description = "Manage the server's XP, including importing or fully resetting XP."


[reaction-roles]
name = "Reaction Roles"
icon = "add_reaction"
description = "Allow users to self-assign roles, including verification roles."
selfPermissions = ["ManageRoles"]


[moderation]
name = "Moderation"
icon = "shield"
description = "Moderation commands for managing users and content."

[moderation.commands.ban]
name = "Ban"
icon = "gavel"
description = "Ban a user (even if they are not in the server)."
permissions = ["BanMembers"]
selfPermissions = ["BanMembers"]

[moderation.commands.kick]
name = "Kick"
icon = "person_remove"
description = "Kick a member from the server."
permissions = ["KickMembers"]
selfPermissions = ["KickMembers"]

[moderation.commands.mute]
name = "Mute"
icon = "volume_off"
description = "Mute a user by assigning them a mute role. This only works on non-members if the Sticky Roles module is enabled."
permissions = ["ModerateMembers"]
selfPermissions = ["ManageRoles"]

[moderation.commands.timeout]
name = "Timeout"
icon = "timer"
description = "Timeout a member or remove their timeout."
permissions = ["ModerateMembers"]
selfPermissions = ["ModerateMembers"]

[moderation.commands.warn]
name = "Warn"
icon = "warning"
description = "DM a warning to a user and log it to their user history."
permissions = ["ModerateMembers"]

[moderation.commands.unban]
name = "Unban"
icon = "manage_accounts"
description = "Unban a user, allowing them to rejoin the server."
permissions = ["BanMembers"]
selfPermissions = ["BanMembers"]

[moderation.commands.unmute]
name = "Unmute"
icon = "volume_up"
description = "Unmute a user by removing their mute role. This only works on non-members if the Sticky Roles module is enabled."
permissions = ["ModerateMembers"]
selfPermissions = ["ManageRoles"]

[moderation.commands.massban]
name = "Massban"
icon = "group_remove"
description = "Ban many users at once."
permissions = ["ManageGuild"]
selfPermissions = ["BanMembers"]

[moderation.commands.history]
name = "View History"
icon = "history"
description = "View a user's history."
permissions = ["ModerateMembers"]
ghost = true

[moderation.commands.delete-history]
name = "Delete History Entry"
icon = "delete"
description = "Remove a single history entry."
permissions = ["ManageGuild"]

[moderation.commands.clear-history]
name = "Clear History"
icon = "manage_history"
description = "Clear a user's history."
permissions = ["ManageGuild"]

[moderation.commands.slowmode]
name = "Slowmode"
icon = "speed"
description = "Set a channel's slowmode."
permissions = ["ManageChannels"]
selfPermissions = ["ManageChannels"]
bypass = true

[moderation.commands.purge]
name = "Purge"
icon = "delete_sweep"
description = "Purge many messages at once."
permissions = ["ManageGuild"]
selfPermissions = ["ManageMessages"]

[moderation.commands.notes]
name = "Notes"
icon = "notes"
description = "Record mod notes for a user."
permissions = ["ModerateMembers"]


[starboard]
name = "Starboard"
icon = "star"
description = "Feature messages that receive a specified reaction."


[automod]
name = "Automod"
icon = "document_scanner"
description = "Automatically scan and filter messages and edits for blocked content."
selfPermissions = [
    "ManageMessages",
    "ManageRoles",
    "ModerateMembers",
    "KickMembers",
    "BanMembers",
]


[sticky-roles]
name = "Sticky Roles"
icon = "replay"
description = "Automatically re-add roles to members when they rejoin the server."
selfPermissions = ["ManageRoles"]
default = false


[custom-roles]
name = "Custom Roles"
icon = "dashboard_customize"
description = "Give boosters and other server supporters the ability to create custom roles."
selfPermissions = ["ManageRoles"]
default = false

[custom-roles.commands.role]
name = "Custom Role"
icon = "format_color_fill"
description = "Manage the user's custom role."
selfPermissions = ["ManageRoles"]
ghost = true


[stats-channels]
name = "Stats Channels"
icon = "insights"
description = "Keep track of server stats with automatically updating channels."
selfPermissions = ["ManageChannels"]


[autoresponder]
name = "Autoresponder"
icon = "bolt"
description = "Automatically respond to certain messages"


[modmail]
name = "Modmail"
icon = "mail"
description = "Allow users to contact staff via direct-messaging the bot."
selfPermissions = ["CreatePublicThreads", "ManageThreads", "ManageChannels"]
default = false

[modmail.commands.modmail]
name = "Modmail"
icon = "mail"
description = "Modmail operation commands."


[tickets]
name = "Tickets"
icon = "confirmation_number"
description = "Allow users to contact staff by creating new private channels at the press of a button."
selfPermissions = ["ManageChannels"]

[tickets.commands.ticket]
name = "Ticket"
icon = "confirmation_number"
description = "Manage tickets."


[nukeguard]
name = "Nukeguard"
icon = "security"
description = "Anti-nuke features to guard against rogue or compromised mods/admins."
selfPermissions = ["BanMembers"]


[suggestions]
name = "Suggestions"
icon = "feedback"
description = "Allow members to give feedback on the server."

[suggestions.commands.suggest]
name = "Suggest"
icon = "feedback"
description = "Make a suggestion."
ghost = true

[suggestions.commands.suggestion]
name = "Manage Suggestions"
icon = "forum"
description = "Answer suggestions and view anonymously submitted suggestions' authors."
permissions = ["ManageGuild"]


[co-op]
name = "Co-op (Genshin Impact)"
icon = "handshake"
description = "Co-op group finding system for Genshin Impact."

[commands.co-op.co-op]
name = "Co-op"
icon = "group"
description = "Find a co-op group."
ghost = true


[feeds]
name = "Feeds"
icon = "rss_feed"
description = "Subscribe to live updates from various other websites."

[feeds.commands.feed]
name = "Feed"
icon = "rss_feed"
description = "Set up or manage feeds."
permissions = ["ManageGuild"]


[count]
name = "Counting Channels"
icon = "123"
description = "Counting channels."
selfPermissions = ["ManageMessages"]

[count.commands.scoreboard]
name = "Scoreboard"
icon = "leaderboard"
description = "View the counting leaderboard."
ghost = true


[giveaways]
name = "Giveaway"
icon = "celebration"
description = "Set up giveaways for server members."

[giveaways.commands.giveaway]
name = "Manage Giveaways"
icon = "celebration"
description = "Manage giveaways."
permissions = ["ManageGuild"]


[reminders]
name = "Reminders"
icon = "event"
description = "Set up reminders to appear in your DMs."

[reminders.commands.reminder]
name = "Reminder"
icon = "event"
description = "Set, list, or manage your reminders."
ghost = true


[reports]
name = "Reports"
icon = "report_problem"
description = "Allow members to report users and messages to moderators."
default = false

[reports.commands."Report User"]
name = "Report User"
icon = "report"
description = "Report a user (user context menu command)."
ghost = true

[reports.commands."Flag Message"]
name = "Flag Message"
icon = "flag"
description = "Flag a message (message context menu command)."
ghost = true

[reports.commands.report]
name = "Report User"
icon = "report"
description = "Report a user (slash command)."
ghost = true

[reports.commands.flag]
name = "Flag Message"
icon = "flag"
description = "Flag a message (slash command)."
ghost = true


[polls]
name = "Polls"
icon = "poll"
description = "Yes/no and multiple-choice polls."

[polls.commands.polls]
name = "Polls"
icon = "poll"
description = "Create and manage polls."
permissions = ["ManageGuild"]


[highlights]
name = "Highlights"
icon = "notifications"
description = "Receive DM notifications for messages matching your filters."

[highlights.commands.highlights]
name = "Highlight"
icon = "notifications"
description = "Manage your highlights."
ghost = true


[utility]
name = "Utility"
icon = "handyman"
description = "Utility commands for server management and other purposes."

[utility.commands.emoji-roles]
name = "Emoji Roles"
icon = "filter_list"
description = "Control which roles can use which server emoji."
permissions = ["ManageGuildExpressions"]
selfPermissions = ["ManageGuildExpressions"]

[utility.commands.help]
name = "Help"
icon = "help"
description = "Get help for the bot."
ghost = true

[utility.commands.info]
name = "Info"
icon = "info"
description = "Get info for a user, role, channel, server, or invite."
ghost = true

[utility.commands.avatar]
name = "Avatar"
icon = "account_box"
description = "View a user's avatar."
ghost = true

[utility.commands.roles]
name = "Roles"
icon = "theater_comedy"
description = "Alter a user's roles."
permissions = ["ManageRoles"]
selfPermissions = ["ManageRoles"]

[utility.commands.format]
name = "Format"
icon = "text_format"
description = "Convert a Discord message element into its source text."
ghost = true

[utility.commands.say]
name = "Say"
icon = "chat"
description = "Say a message."
permissions = ["ManageGuild"]

[utility.commands.code]
name = "Code"
icon = "redeem"
description = "Display a Genshin Impact gift code."
ghost = true

[utility.commands.qr]
name = "QR"
icon = "qr_code_scanner"
description = "Convert any text into a QR code."
ghost = true

[utility.commands.tex]
name = "Render LaTeX"
icon = "image"
description = "Render LaTeX to a PNG file."
ghost = true

[utility.commands.convert]
name = "Convert Units"
icon = "currency_exchange"
description = "Convert between common units or between currencies."
ghost = true

[utility.commands.snowflake]
name = "Snowflake"
icon = "ac_unit"
description = "Deconstruct a Discord snowflake (ID)."
ghost = true

[utility.commands.role-accessibility]
name = "Role Accessibility"
icon = "accessibility"
description = "Check if role colors' contrasts meet accessibility standards."
ghost = true

[utility.commands."Extract IDs"]
name = "Extract IDs"
icon = "123"
description = "Extract all IDs from a message for easier copying."
ghost = true


[sticky-messages]
name = "Sticky Messages"
icon = "sticky_note_2"
description = "Set messages to stick to the bottom of a channel."

[sticky-messages.commands.stick]
name = "Stick"
icon = "label"
description = "Set the channel's sticky message."
permissions = ["ManageChannels"]

[sticky-messages.commands.unstick]
name = "Stick"
icon = "label_off"
description = "Remove the channel's sticky message."
permissions = ["ManageChannels"]

[sticky-messages.commands.sticklist]
name = "List Sticky Messages"
icon = "list"
description = "List the server's sticky messages."
permissions = ["ManageChannels"]


[fun]
name = "Fun"
icon = "attractions"
description = "Fun commands that are mostly pointless/unimportant."

[fun.commands.random]
name = "Random"
icon = "shuffle"
description = "Random-related functions."
ghost = true
